[project]
name = "stock-backtest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "최원혁", email = "wonhyuk8944@gmail.com" }
]
requires-python = ">=3.11,<3.14"
dependencies = [
    "duckdb>=1.5.5",
    "pandas>=2.2.0,<3.0",
    "pyarrow>=25.0.1",
    "python-dotenv>=1.2.3",
    "pyyaml>=6.0.3",
    "requests>=2.34.2",
    "tqdm>=4.70.0",
]

[project.scripts]
stock-backtest = "stock_backtest:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"
